# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-container
  name: test-container
  namespace: default
spec:
  ports:
   - name: http
     nodePort: 30106
     port: 8080
     protocol: TCP
     targetPort: 8080
  selector:
    app: test-container
  sessionAffinity: None
  type: LoadBalancer
